# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: true
contact_links:
  - name: Security vulnerability report
    url: https://www.nvidia.com/object/submit-security-vulnerability.html
    about: Please do not report security vulnerabilities through GitHub issues.
