---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 18789
      targetPort: 18789
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
